import scrapy

class Product(scrapy.Item):
    Overdue_Since = scrapy.Field()
    No_of_Installments_Overdue = scrapy.Field()
    Installment_Start_Date = scrapy.Field()
    Installment_Overdue = scrapy.Field()
    Principal_Overdue = scrapy.Field()
    Interest_Overdue = scrapy.Field()
    Charges_Overdue = scrapy.Field()
    Last_Payment_Date = scrapy.Field()
    Last_Payment_Amount = scrapy.Field()
    Bucket = scrapy.Field()
    cif_cid = scrapy.Field()
    # customer_name = scrapy.Field()
    Account_no = scrapy.Field()
    Product_Type = scrapy.Field()
    Application_ID = scrapy.Field()
    Net_Disbursal_Amount = scrapy.Field()
    product = scrapy.Field()
    Branch_Code = scrapy.Field()
    Frequency = scrapy.Field()
    Scheme = scrapy.Field()
    Loan_Disbursed = scrapy.Field()
    Next_Due_Amount = scrapy.Field()
    Installment_Amount = scrapy.Field()
    Billed_Amount = scrapy.Field()
    Balance_O_S = scrapy.Field()
    Principal_Outstanding = scrapy.Field()
    Interest_Outstanding = scrapy.Field()
    Next_Due_Date = scrapy.Field()
    Interest_Type = scrapy.Field()
    Interest_Rate_percentage = scrapy.Field()
    Tenure = scrapy.Field()
    Account_Status = scrapy.Field()
    Non_Instrument_Based_Repayment = scrapy.Field()
    Last_Bounce_Date = scrapy.Field()
    Written_Off_Amount = scrapy.Field()
    Total_Repayment_Amount = scrapy.Field()
    Maturity_Date = scrapy.Field()
    Disbursal_Date = scrapy.Field()
    Principal_Outstanding_Amount = scrapy.Field()
    Principal_Overdue = scrapy.Field()
    Interest_Outstanding_Amount = scrapy.Field()
    Interest_Overdue_Amount = scrapy.Field()
    Late_Fees = scrapy.Field()
    scrape_date = scrapy.Field()


# class product_items(scrapy.Item):
#     res = scrapy.Field()